server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:jira}
    preferIpAddress: ${PREFER_IP:false}
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:registry}:${SERVICE_REGISTRY_PORT:8761}/eureka/

rp:
  mongo:
    host: mongodb
    port: 27017
    dbName: reportportal
    user:
    password:

spring:
  redis:
    host: redis
    port: 6379
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:jira}
        prefer-ip-address: false
